In [1]:
import pandas as pd
import numpy as np
import csv

In [9]:
match = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_ground_truth.tsv', sep='\t', quoting=csv.QUOTE_NONE,
    dtype=str,)
match.head(24)

   source1_entity_id                                 matched_entity_ids
0          S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1        S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2       S1-343815751                          S2-479876582,S3-878454467
3       S1-656753428              S2-153058913,S2-24659151,S3-679606215
4       S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...
5        S1-18727616  S2-755677256,S3-187831601,S3-641489370,S3-4762...
6       S1-318373630                          S2-660036492,S3-804600254
7        S1-86989137                          S3-274817120,S3-312496301
8        S1-29845983                          S2-648035184,S3-588502663
9       S1-789009573              S2-383871912,S3-74481402,S3-576451439
10      S1-730934468                          S2-356983532,S3-352439310
11        S1-7293388  S2-7028416,S2-442723188,S2-157073701,S3-523120965
12      S1-546142636  S2-487600131,S2-582477216,S2-392804085,S3-2000...
13      S1-274126313  S2-736616474,S2-680265918,S2-51486805,S3-92563...
14      S1-145361722              S2-120366543,S2-939389287,S3-96572514
15      S1-503957000  S2-994658326,S2-235117490,S2-353308450,S2-1732...
16      S1-692000596                          S2-580419223,S3-164220452
17      S1-561341312                          S2-483615364,S3-619529814
18      S1-777597828                          S2-836452886,S3-413669121
19      S1-282467635                          S2-938895481,S3-138350041
20      S1-727602285  S2-976870196,S2-947230367,S2-23141904,S2-13866...
21      S1-302869473                                                NaN
22       S1-65263544  S2-881122703,S2-998270769,S2-180463458,S3-4034...
23      S1-840162906  S2-129529678,S3-800978181,S3-139858754,S3-7626...

In [ ]:
match.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2206821 entries, 0 to 2206820
Data columns (total 2 columns):
 #   Column              Dtype
---  ------              -----
 0   source1_entity_id   object
 1   matched_entity_ids  object
dtypes: object(2)
memory usage: 33.7+ MB

In [3]:
train_src1 = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_source1.tsv',sep='\t')
train_src1.head()

,entity_id,business_name,business_address,country
0,S1-925783039,Orelee's Barbershop,"1795 Westchester Drive, High Point, NC",US
1,S1-773889195,Prime Money,"17560 Ellis Road, Tahlequah, OK",US
2,S1-377745466,B+ Retail Inc,"1712 Montebello Avenue, Phoenix, AZ",US
3,S1-133037285,Christ Chapel,"2100 Cameron Drive, Unit APARTMENT G, Dundalk, MD",US
4,S1-755362802,Prabhav Business Center,"797, Lake Town Block A, Kolkata, Howrah, West ...",India

In [ ]:
train_src2 = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_source2.tsv',sep='\t')
train_src2.head()

In [ ]:
train_src3 = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_source3.tsv',sep='\t')
train_src3.head()

In [10]:
pip install deep-translator

Collecting deep-translator
  Downloading deep_translator-1.11.4-py3-none-any.whl.metadata (30 kB)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from deep-translator) (4.14.3)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from deep-translator) (2.32.5)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ps302\anaconda3\envs\genai\lib\site-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2026.2.25)
Downloading deep_translator-1.11.4-py3-none-any.whl (42 kB)
Installing collected packages: deep-translator
Successfully installed deep-translator-1.11.4
Note: you may need to restart the kernel to use updated packages.

In [4]:
from deep_translator import GoogleTranslator

# Automatically detects the source language and translates to English
text_to_translate = "അൽ കൺസ്ട്രക്ഷൻസ് ഫുഡ്സ് പ്രൈവറ്റ് ലിമിറ്റഡ്"
translated = GoogleTranslator(source='auto', target='en').translate(text_to_translate)

print(translated)
# Output: Al Constructions Foods Private Limited

TooManyRequests: Server Error: You made too many requests to the server.According to google, you are allowed to make 5 requests per secondand up to 200k requests per day. You can wait and try again later oryou can try the translate_batch function