In [2]:
import pandas as pd
import numpy as np
import sys

In [3]:
import sys
import os

backend_path = os.path.abspath("../../")
sys.path.insert(0, backend_path)

In [4]:
backend_path

'c:\\Users\\ps302\\OneDrive\\Desktop\\Amazon\\business-entity-resolution'

In [5]:
match = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_ground_truth.tsv',sep='\t')
match.sample()

       source1_entity_id         matched_entity_ids
855750      S1-992565566  S2-952100195,S3-630144054

In [6]:
match.head()

  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751                          S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

In [23]:
for i in range(2):
    print(match.iloc[i,:])

source1_entity_id                                             S1-965667
matched_entity_ids    S2-681193310,S2-743505751,S3-775321672,S3-1129...
Name: 0, dtype: object
source1_entity_id                                           S1-55344266
matched_entity_ids    S2-249013014,S2-197070651,S3-478195123,S3-3843...
Name: 1, dtype: object

In [8]:
train_src1 = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_source1.tsv',sep='\t')
train_src1["country"].value_counts()

country
US       1323633
India     883188
Name: count, dtype: int64

In [26]:
train_src2 = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_source2.tsv',sep='\t')
train_src2.head()

,entity_id,business_name,business_address,country
0,S2-166376419,राम मार्केटिंग प्राइवेट लिमिटेड,"KH NO. -570/13, NEW DELHI, WEST DELHI, Delhi",India
1,S2-764573417,-- Holloway Peak Inc Seafood,"105 ELM ST, MORGANTON, NC",US
2,S2-639257739,आदित्य प्रॉपर्टीज एलएलपी,"G-3/571, GULMOHAR COLONY, BHOPAL, Madhya Pradesh",India
3,S2-163963287,Summit Inc,"GREENSBORO, NC, 19 1/2 STARDUST TRAIL",US
4,S2-49942811,Delta Tetlecommunication Inc,"914 PIERPONT AVE, CLEVELAND, OH",US

In [27]:
train_src3 = pd.read_csv(r'C:\Users\ps302\OneDrive\Desktop\Amazon\business-entity-resolution\dataset\train\train_source3.tsv',sep='\t')
train_src3.head()

,entity_id,business_name,business_address,country
0,S3-202863386,wilfordhancock.com,"Mack Rd, Haltom City, Texas",US
1,S3-859268022,International South Consultants Private Ltd,NaN,India
2,S3-22467283,LLC Moncada Léarning Center,"5780 Fawn Ct, Fort Worth, Texas",US
3,S3-671162755,Moyna's Coffee,"1 Ivanhoe Ave, PO Box 6009, Cincinnati, Ohio",US
4,S3-960981775,Pvt. EFS Print Ventures Ltd.,"Door No 183, 41St Cross, 22Nd Main 9Th Block J...",India